### ISSUE TITLE
[BUG]: Installation fails on Window with charmap error

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/ucx#2251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to install UCX using GITBASH CLI on windows we get an error during the dashboard installation phase. Version 2.9.0

### Expected Behavior

UCX installation is expected to succeed.

### Cloud

Azure

### Operating System

Windows

### Version

latest via Databricks CLI

### Relevant log output

```shell
ERROR [d.l.blueprint.parallel][installing_components_1] installing components(WindowsPath('C:/Users/LENOVO/.databricks/labs/ucx/lib/src/databricks/labs/ucx/queries/assessment/estimates'), parent_path='/Applications/ucx/dashboards') task failed: 'charmap' codec can't decode byte 0x9d in position 1020: character maps to <undefined>: Traceback (most recent call last):    
  File "C:\Users\LENOVO\.databricks\labs\ucx\state\venv\Lib\site-packages\databricks\labs\blueprint\parallel.py", line 158, in inner
    return func(*args, **kwargs), None
```

**Comment by pritishpai** [comment]
Related: https://github.com/mwouts/jupytext/issues/770

**Comment by tarikcurto** [comment]
It was fixed in this PR https://github.com/databrickslabs/ucx/pull/2234

**Comment by JCZuurmond** [comment]
@FastLee : Could you reopen the issue after confirming that the issue still holds for the master? As @tarikcurto mentioned, it is fixed in #2234
