### ISSUE TITLE
Assessment task failed in Jobs crawler

### ISSUE THREAD

**Issue by dipankarkush-db** [databrickslabs/ucx#503]
The Assessment task failed in Jobs crawler

Stack Trace Below-

```bash
20:07:43 DEBUG [databricks.sdk] {MainThread} GET /api/2.0/policies/clusters/get?policy_id=C9610A17BF000091
< 200 OK
< {
<   "created_at_timestamp": 1630349338000,
<   "definition": "{\"autoscale.max_workers\":{\"defaultValue\":8,\"isOptional\":true,\"maxValue\":64,\"type\":\"range\"},\"auto... (1861 more bytes)",
<   "is_default": false,
<   "name": "TmCil - Job Clusters",
<   "policy_id": "C9610A17BF000091"
< }
20:07:43 DEBUG [databricks.sdk] {MainThread} GET /api/2.0/dbfs/read?path=/init-scripts/foundation-components.sh
< 200 OK
< {
<   "bytes_read": 307,
<   "data": "CmVjaG8gJy0tLS1JbnN0YWxsaW5nIExhdGVzdCBGb3VuZGF0aW9uIENvbXBvbmVudHMtLS0tJwpwaXAgaW5zdGFsbCBlZmZv... (316 more bytes)"
< }
20:07:43 DEBUG [databricks.sdk] {MainThread} GET /api/2.0/dbfs/read?path=/databricks/unravel/unravel-db-sensor-archive/dbin/install-unravel.sh
< 200 OK
< {
<   "bytes_read": 811,
<   "data": "IyEvYmluL2Jhc2gKIwojIFJ1bnMgVW5yYXZlbCBJbmlRVI9MQp3aGlsZSBbICEgLWQgIi9kYmZz... (988 more bytes)"
< }
20:07:43 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx_sd.jobs] found 491 new records for jobs
20:07:43 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/s210@ddd.com/.ucx/logs/assessment/run-243/assess_jobs.log` locally to troubleshoot with more details. [CANNOT_BE_NONE] Argument `obj` can not be None.
20:07:43 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 218, in assess_jobs
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 557, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 230, in _snapshot
    self._append_records(loaded_records)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 235, in _append_records
    self._backend.save_table(self._full_name, items, self._klass, mode="append")
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 135, in save_table
    df = self._spark.createDataFrame(rows, self._schema_for(rows[0]))
  File "/databricks/spark/python/pyspark/instrumentation_utils.py", line 47, in wrapper
    res = func(*args, **kwargs)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1507, in createDataFrame
    return self._create_dataframe(
  File "/databricks/spark/python/pyspark/sql/session.py", line 1557, in _create_dataframe
    rdd, struct = self._createFromLocal(map(prepare, data), schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1135, in _createFromLocal
    internal_data, struct = self._wrap_data_schema(data, schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1099, in _wrap_data_schema
    data = list(data)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1523, in prepare
    verify_func(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 2206, in verify
    verify_value(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 2183, in verify_struct
    verifier(d.get(f))
  File "/databricks/spark/python/pyspark/sql/types.py", line 2205, in verify
    if not verify_nullability(obj):
  File "/databricks/spark/python/pyspark/sql/types.py", line 2008, in verify_nullability
    raise PySparkValueError(
pyspark.errors.exceptions.base.PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.
```

**Comment by william-conti** [comment]
Should also be fixed by https://github.com/databrickslabs/ucx/pull/485

**Comment by sureshd-8451** [comment]
I am also still facing this error with the main branch.

PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.
---------------------------------------------------------------------------
PySparkValueError                         Traceback (most recent call last)
File ~/.ipykernel/2605/command--1-1241369258:18
     15 entry = [ep for ep in metadata.distribution("databricks_labs_ucx").entry_points if ep.name == "runtime"]
     16 if entry:
     17   # Load and execute the entrypoint, assumes no parameters
---> 18   entry[0].load()()
     19 else:
     20   import databricks_labs_ucx

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py:445, in main(*argv)
    443 if len(argv) == 0:
    444     argv = sys.argv
--> 445 trigger(*argv)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py:149, in trigger(*argv)
    146         f.write(f"[run #{workflow_run_id}](/#job/{job_id}/run/{workflow_run_id})\n")
    148 try:
--> 149     current_task.fn(cfg)
    150 except BaseException as error:
    151     log_file_for_cli = str(log_file).lstrip("/Workspace")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py:218, in assess_jobs(cfg)
    216 ws = WorkspaceClient(config=cfg.to_databricks_config())
    217 crawler = JobsCrawler(ws, RuntimeBackend(), cfg.inventory_database)
--> 218 crawler.snapshot()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py:591, in JobsCrawler.snapshot(self)
    590 def snapshot(self) -> list[JobInfo]:
--> 591     return self._snapshot(self._try_fetch, self._crawl)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py:230, in CrawlerBase._snapshot(self, fetcher, loader)
    228 logger.debug(f"[{self._full_name}] crawling new batch for {self._table}")
    229 loaded_records = list(loader())
--> 230 self._append_records(loaded_records)
    231 return loaded_records

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py:235, in CrawlerBase._append_records(self, items)
    233 def _append_records(self, items):
    234     logger.debug(f"[{self._full_name}] found {len(items)} new records for {self._table}")
--> 235     self._backend.save_table(self._full_name, items, self._klass, mode="append")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py:135, in RuntimeBackend.save_table(self, full_name, rows, klass, mode)
    133     return
    134 # pyspark deals well with lists of dataclass instances, as long as schema is provided
--> 135 df = self._spark.createDataFrame(rows, self._schema_for(rows[0]))
    136 df.write.saveAsTable(full_name, mode=mode)

File /databricks/spark/python/pyspark/instrumentation_utils.py:47, in _wrap_function.<locals>.wrapper(*args, **kwargs)
     45 start = time.perf_counter()
     46 try:
---> 47     res = func(*args, **kwargs)
     48     logger.log_success(
     49         module_name, class_name, function_name, time.perf_counter() - start, signature
     50     )
     51     return res

File /databricks/spark/python/pyspark/sql/session.py:1507, in SparkSession.createDataFrame(self, data, schema, samplingRatio, verifySchema)
   1502 if has_pandas and isinstance(data, pd.DataFrame):
   1503     # Create a DataFrame from pandas DataFrame.
   1504     return super(SparkSession, self).createDataFrame(  # type: ignore[call-overload]
   1505         data, schema, samplingRatio, verifySchema
   1506     )
-> 1507 return self._create_dataframe(
   1508     data, schema, samplingRatio, verifySchema  # type: ignore[arg-type]
   1509 )

File /databricks/spark/python/pyspark/sql/session.py:1557, in SparkSession._create_dataframe(self, data, schema, samplingRatio, verifySchema)
   1555     rdd, struct = self._createFromRDD(data.map(prepare), schema, samplingRatio)
   1556 else:
-> 1557     rdd, struct = self._createFromLocal(map(prepare, data), schema)
   1558 jrdd = self._jvm.SerDeUtil.toJavaArray(rdd._to_java_object_rdd())
   1559 jdf = self._jsparkSession.applySchemaToPythonRDD(jrdd.rdd(), struct.json())

File /databricks/spark/python/pyspark/sql/session.py:1135, in SparkSession._createFromLocal(self, data, schema)
   1127 def _createFromLocal(
   1128     self, data: Iterable[Any], schema: Optional[Union[DataType, List[str]]]
   1129 ) -> Tuple["RDD[Tuple]", StructType]:
   1130     """
   1131     Create an RDD for DataFrame from a list or pandas.DataFrame, returns the RDD and schema.
   1132     This would be broken with table acl enabled as user process does not have permission to
   1133     write temp files.
   1134     """
-> 1135     internal_data, struct = self._wrap_data_schema(data, schema)
   1136     return self._sc.parallelize(internal_data), struct

File /databricks/spark/python/pyspark/sql/session.py:1099, in SparkSession._wrap_data_schema(self, data, schema)
   1094 def _wrap_data_schema(
   1095     self, data: Iterable[Any], schema: Optional[Union[DataType, List[str]]]
   1096 ) -> Tuple[Iterable[Tuple], StructType]:
   1097     # make sure data could consumed multiple times
   1098     if not isinstance(data, list):
-> 1099         data = list(data)
   1101     if schema is None or isinstance(schema, (list, tuple)):
   1102         struct = self._inferSchemaFromList(data, names=schema)

File /databricks/spark/python/pyspark/sql/session.py:1523, in SparkSession._create_dataframe.<locals>.prepare(obj)
   1521 @no_type_check
   1522 def prepare(obj):
-> 1523     verify_func(obj)
   1524     return obj

File /databricks/spark/python/pyspark/sql/types.py:2206, in _make_type_verifier.<locals>.verify(obj)
   2204 def verify(obj: Any) -> None:
   2205     if not verify_nullability(obj):
-> 2206         verify_value(obj)

File /databricks/spark/python/pyspark/sql/types.py:2183, in _make_type_verifier.<locals>.verify_struct(obj)
   2181     d = obj.__dict__
   2182     for f, verifier in verifiers:
-> 2183         verifier(d.get(f))
   2184 else:
   2185     raise PySparkTypeError(
   2186         error_class="CANNOT_ACCEPT_OBJECT_IN_TYPE",
   2187         message_parameters={
   (...)
   2191         },
   2192     )

File /databricks/spark/python/pyspark/sql/types.py:2205, in _make_type_verifier.<locals>.verify(obj)
   2204 def verify(obj: Any) -> None:
-> 2205     if not verify_nullability(obj):
   2206         verify_value(obj)

File /databricks/spark/python/pyspark/sql/types.py:2008, in _make_type_verifier.<locals>.verify_nullability(obj)
   2006         return True
   2007     else:
-> 2008         raise PySparkValueError(
   2009             error_class="CANNOT_BE_NONE",
   2010             message_parameters={"arg_name": "obj"},
   2011         )
   2012 else:
   2013     return False

PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.
UCX v0.5.1+920231027104652
Scans through all the jobs and identifies those that are not compatible with UC. The list of all the jobs is
stored in the `$inventory.jobs` table.

It looks for:
  - Clusters with Databricks Runtime (DBR) version earlier than 11.3
  - Clusters using Passthrough Authentication
  - Clusters with incompatible Spark config tags
  - Clusters referencing DBFS locations in one or more config options

14:56  INFO [d.labs.ucx] After job finishes, see debug logs at /Workspace/Users/s210302@8451.com/.ucx/logs/assessment/run-127051704469592/assess_jobs.log
14:57  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C9643F54D4001C9C. The cluster policy was deleted. Error: Can't find a cluster policy with id: C9643F54D4001C9C.
14:57  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C96178C1CF000327. The cluster policy was deleted. Error: Can't find a cluster policy with id: C96178C1CF000327.
14:57  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C96178C1CF000327. The cluster policy was deleted. Error: Can't find a cluster policy with id: C96178C1CF000327.
14:57  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C96178C1CF000327. The cluster policy was deleted. Error: Can't find a cluster policy with id: C96178C1CF000327.

UCX v0.5.1+920231027104652
Scans through all the jobs and identifies those that are not compatible with UC. The list of all the jobs is
stored in the `$inventory.jobs` table.

It looks for:
  - Clusters with Databricks Runtime (DBR) version earlier than 11.3
  - Clusters using Passthrough Authentication
  - Clusters with incompatible Spark config tags
  - Clusters referencing DBFS locations in one or more config options

14:56  INFO [d.labs.ucx] After job finishes, see debug logs at /Workspace/Users/s210302@8451.com/.ucx/logs/assessment/run-127051704469592/assess_jobs.log
14:57  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C9643F54D4001C9C. The cluster policy was deleted. Error: Can't find a cluster policy with id: C9643F54D4001C9C.
14:57  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C96178C1CF000327. The cluster policy was deleted. Error: Can't find a cluster policy with id: C96178C1CF000327.
14:57  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C96178C1CF000327. The cluster policy was deleted. Error: Can't find a cluster policy with id: C96178C1CF000327.
14:57  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C96178C1CF000327. The cluster policy was deleted. Error: Can't find a cluster policy with id: C96178C1CF000327.
14:58  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C961B9761B00015C. The cluster policy was deleted. Error: Can't find a cluster policy with id: C961B9761B00015C.
14:58  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C961B9761B00015C. The cluster policy was deleted. Error: Can't find a cluster policy with id: C961B9761B00015C.
14:58  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C961B9761B00015C. The cluster policy was deleted. Error: Can't find a cluster policy with id: C961B9761B00015C.
14:58  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C961B9761B00015C. The cluster policy was deleted. Error: Can't find a cluster policy with id: C961B9761B00015C.
14:58  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C961B9761B00015C. The cluster policy was deleted. Error: Can't find a cluster policy with id: C961B9761B00015C.
14:58  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C961B9761B00015C. The cluster policy was deleted. Error: Can't find a cluster policy with id: C961B9761B00015C.
14:58  WARN [d.l.u.assessment.crawlers] Error retrieving cluster policy C96178C1CF0003E4. The cluster policy was deleted. Error: Can't find a cluster policy with id: C96178C1CF0003E4.
14:58 ERROR [d.labs.ucx] Task crashed. Execute `databricks workspace export /Users/s210302@8451.com/.ucx/logs/assessment/run-127051704469592/assess_jobs.log` locally to troubleshoot with more details. [CANNOT_BE_NONE] Argument `obj` can not be None.

**Comment by jia-li-fl** [comment]
Hi, I also have a similar/same issue.

19:27:15 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx.jobs] found 360 new records for jobs
19:27:15 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/person@org/.ucx/logs/assessment/run-#########/assess_jobs.log` locally to troubleshoot with more details. [CANNOT_BE_NONE] Argument `obj` can not be None.
19:27:15 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 218, in assess_jobs
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 557, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 230, in _snapshot
    self._append_records(loaded_records)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 235, in _append_records
    self._backend.save_table(self._full_name, items, self._klass, mode="append")
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 135, in save_table
    df = self._spark.createDataFrame(rows, self._schema_for(rows[0]))
  File "/databricks/spark/python/pyspark/instrumentation_utils.py", line 47, in wrapper
    res = func(*args, **kwargs)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1507, in createDataFrame
    return self._create_dataframe(
  File "/databricks/spark/python/pyspark/sql/session.py", line 1557, in _create_dataframe
    rdd, struct = self._createFromLocal(map(prepare, data), schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1135, in _createFromLocal
    internal_data, struct = self._wrap_data_schema(data, schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1099, in _wrap_data_schema
    data = list(data)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1523, in prepare
    verify_func(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 2206, in verify
    verify_value(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 2183, in verify_struct
    verifier(d.get(f))
  File "/databricks/spark/python/pyspark/sql/types.py", line 2205, in verify
    if not verify_nullability(obj):
  File "/databricks/spark/python/pyspark/sql/types.py", line 2008, in verify_nullability
    raise PySparkValueError(
pyspark.errors.exceptions.base.PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.

**Comment by dipankarkush-db** [comment]
stack trace -

`14:58:20 DEBUG [databricks.labs.ucx.framework.crawlers] {MainThread} [hive_metastore.ucx_ds.jobs] found 746 new records for jobs
14:58:20 ERROR [databricks.labs.ucx] {MainThread} Task crashed. Execute `databricks workspace export /Users/111@111.com/.ucx/logs/assessment/run-111/assess_jobs.log` locally to troubleshoot with more details. [CANNOT_BE_NONE] Argument `obj` can not be None.
14:58:20 DEBUG [databricks] {MainThread} Task crash details
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/tasks.py", line 149, in trigger
    current_task.fn(cfg)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/runtime.py", line 218, in assess_jobs
    crawler.snapshot()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/assessment/crawlers.py", line 591, in snapshot
    return self._snapshot(self._try_fetch, self._crawl)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 230, in _snapshot
    self._append_records(loaded_records)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 235, in _append_records
    self._backend.save_table(self._full_name, items, self._klass, mode="append")
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/labs/ucx/framework/crawlers.py", line 135, in save_table
    df = self._spark.createDataFrame(rows, self._schema_for(rows[0]))
  File "/databricks/spark/python/pyspark/instrumentation_utils.py", line 47, in wrapper
    res = func(*args, **kwargs)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1507, in createDataFrame
    return self._create_dataframe(
  File "/databricks/spark/python/pyspark/sql/session.py", line 1557, in _create_dataframe
    rdd, struct = self._createFromLocal(map(prepare, data), schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1135, in _createFromLocal
    internal_data, struct = self._wrap_data_schema(data, schema)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1099, in _wrap_data_schema
    data = list(data)
  File "/databricks/spark/python/pyspark/sql/session.py", line 1523, in prepare
    verify_func(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 2206, in verify
    verify_value(obj)
  File "/databricks/spark/python/pyspark/sql/types.py", line 2183, in verify_struct
    verifier(d.get(f))
  File "/databricks/spark/python/pyspark/sql/types.py", line 2205, in verify
    if not verify_nullability(obj):
  File "/databricks/spark/python/pyspark/sql/types.py", line 2008, in verify_nullability
    raise PySparkValueError(
pyspark.errors.exceptions.base.PySparkValueError: [CANNOT_BE_NONE] Argument `obj` can not be None.`

**Comment by larsgeorge-db** [comment]
> Should also be fixed by #485

Since that issue is merged, does it NOT fix the above then?

**Comment by william-conti** [comment]
Errors like this that are caused by empty owners are fixed in #485, everyone should use the main branch (v0.5.1) and destroy previously created tables. I've tested it in our demo environment and didn't faced an issue for this.

However @sureshd-8451 error is a separate issue, we don't catch cluster policies that doesn't exist

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
